export const NatoRangeTable = [
  {
    Shell_type: "HE",
    round_name: "M821",
    rangeTableList: [
      {
        value: 0,
        fix_mil: 6,
        minMaxRange: [50, 400],
        range: [
          {
            r: 50,
            mils: 1540,
            time: 13.2,
            timeDiff: 0,
          },
          {
            r: 100,
            mils: 1479,
            time: 13.2,
            timeDiff: 0.2,
          },
          {
            r: 150,
            mils: 1416,
            time: 13.0,
            timeDiff: 0.2,
          },
          {
            r: 200,
            mils: 1350,
            time: 12.8,
            timeDiff: 0.2,
          },
          {
            r: 250,
            mils: 1279,
            time: 12.6,
            timeDiff: 0.3,
          },
          {
            r: 300,
            mils: 1201,
            time: 12.3,
            timeDiff: 0.6,
          },
          {
            r: 350,
            mils: 1106,
            time: 11.7,
            timeDiff: 1,
          },
          {
            r: 400,
            mils: 955,
            time: 10.7,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 1,
        fix_mil: 14,
        minMaxRange: [100, 900],
        range: [
          {
            r: 100,
            mils: 1547,
            time: 20.0,
            timeDiff: 0.1,
          },
          {
            r: 200,
            mils: 1492,
            time: 19.9,
            timeDiff: 0.1,
          },
          {
            r: 300,
            mils: 1437,
            time: 19.7,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1378,
            time: 19.5,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1317,
            time: 19.2,
            timeDiff: 0.2,
          },
          {
            r: 600,
            mils: 1249,
            time: 18.8,
            timeDiff: 0.2,
          },
          {
            r: 700,
            mils: 1174,
            time: 18.3,
            timeDiff: 0.4,
          },
          {
            r: 800,
            mils: 1085,
            time: 17.5,
            timeDiff: 0.6,
          },
          {
            r: 900,
            mils: 954,
            time: 16.1,
            timeDiff: 1.8,
          },
        ],
      },
      {
        value: 2,
        fix_mil: 24,
        minMaxRange: [200, 1600],
        range: [
          {
            r: 200,
            mils: 1538,
            time: 26.6,
            timeDiff: 0,
          },
          {
            r: 300,
            mils: 1507,
            time: 26.5,
            timeDiff: 0,
          },
          {
            r: 400,
            mils: 1475,
            time: 26.4,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1443,
            time: 26.3,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1410,
            time: 26.2,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1376,
            time: 26.0,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1341,
            time: 25.8,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1305,
            time: 25.2,
            timeDiff: 0.1,
          },
          {
            r: 1000,
            mils: 1266,
            time: 25.2,
            timeDiff: 0.1,
          },
          {
            r: 1100,
            mils: 1225,
            time: 24.9,
            timeDiff: 0.2,
          },
          {
            r: 1200,
            mils: 1180,
            time: 24.4,
            timeDiff: 0.2,
          },
          {
            r: 1300,
            mils: 1132,
            time: 23.9,
            timeDiff: 0.3,
          },
          {
            r: 1400,
            mils: 1076,
            time: 23.2,
            timeDiff: 0.4,
          },
          {
            r: 1500,
            mils: 1009,
            time: 22.3,
            timeDiff: 0.6,
          },
          {
            r: 1600,
            mils: 912,
            time: 20.9,
            timeDiff: 1.9,
          },
        ],
      },
      {
        value: 3,
        fix_mil: 33,
        minMaxRange: [300, 2300],
        range: [
          {
            r: 300,
            mils: 1534,
            time: 31.7,
            timeDiff: 0,
          },
          {
            r: 400,
            mils: 1511,
            time: 31.6,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1489,
            time: 31.6,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1466,
            time: 31.5,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1442,
            time: 31.4,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1419,
            time: 31.3,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1395,
            time: 31.1,
            timeDiff: 0.1,
          },
          {
            r: 1000,
            mils: 1370,
            time: 31.0,
            timeDiff: 0.1,
          },
          {
            r: 1100,
            mils: 1344,
            time: 30.8,
            timeDiff: 0.1,
          },
          {
            r: 1200,
            mils: 1318,
            time: 30.6,
            timeDiff: 0.1,
          },
          {
            r: 1300,
            mils: 1291,
            time: 30.3,
            timeDiff: 0.1,
          },
          {
            r: 1400,
            mils: 1263,
            time: 30.1,
            timeDiff: 0.2,
          },
          {
            r: 1500,
            mils: 1233,
            time: 29.7,
            timeDiff: 0.1,
          },
          {
            r: 1600,
            mils: 1202,
            time: 29.4,
            timeDiff: 0.2,
          },
          {
            r: 1700,
            mils: 1169,
            time: 29.0,
            timeDiff: 0.2,
          },
          {
            r: 1800,
            mils: 1133,
            time: 28.5,
            timeDiff: 0.2,
          },
          {
            r: 1900,
            mils: 1094,
            time: 28.0,
            timeDiff: 0.3,
          },
          {
            r: 2000,
            mils: 1051,
            time: 27.3,
            timeDiff: 0.4,
          },
          {
            r: 2100,
            mils: 999,
            time: 26.5,
            timeDiff: 0.5,
          },
          {
            r: 2200,
            mils: 931,
            time: 25.3,
            timeDiff: 0.9,
          },
          {
            r: 2300,
            mils: 801,
            time: 22.7,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 4,
        fix_mil: 42,
        minMaxRange: [400, 2900],
        range: [
          {
            r: 400,
            mils: 1531,
            time: 36.3,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1514,
            time: 36.2,
            timeDiff: 0,
          },
          {
            r: 600,
            mils: 1496,
            time: 36.2,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1478,
            time: 36.1,
            timeDiff: 0,
          },
          {
            r: 800,
            mils: 1460,
            time: 36.0,
            timeDiff: 0,
          },
          {
            r: 900,
            mils: 1442,
            time: 35.9,
            timeDiff: 0,
          },
          {
            r: 1000,
            mils: 1424,
            time: 35.9,
            timeDiff: 0,
          },
          {
            r: 1100,
            mils: 1405,
            time: 35.7,
            timeDiff: 0.1,
          },
          {
            r: 1200,
            mils: 1385,
            time: 35.6,
            timeDiff: 0.1,
          },
          {
            r: 1300,
            mils: 1366,
            time: 35.4,
            timeDiff: 0.1,
          },
          {
            r: 1400,
            mils: 1346,
            time: 35.3,
            timeDiff: 0.1,
          },
          {
            r: 1500,
            mils: 1326,
            time: 35.1,
            timeDiff: 0.1,
          },
          {
            r: 1600,
            mils: 1305,
            time: 34.9,
            timeDiff: 0.1,
          },
          {
            r: 1700,
            mils: 1283,
            time: 34.6,
            timeDiff: 0.1,
          },
          {
            r: 1800,
            mils: 1261,
            time: 34.4,
            timeDiff: 0.1,
          },
          {
            r: 1900,
            mils: 1238,
            time: 34.1,
            timeDiff: 0.1,
          },
          {
            r: 2000,
            mils: 1214,
            time: 33.8,
            timeDiff: 0.1,
          },
          {
            r: 2100,
            mils: 1188,
            time: 33.5,
            timeDiff: 0.2,
          },
          {
            r: 2200,
            mils: 1162,
            time: 33.1,
            timeDiff: 0.2,
          },
          {
            r: 2300,
            mils: 1134,
            time: 32.7,
            timeDiff: 0.2,
          },
          {
            r: 2400,
            mils: 1104,
            time: 32.2,
            timeDiff: 0.2,
          },
          {
            r: 2500,
            mils: 1070,
            time: 31.7,
            timeDiff: 0.3,
          },
          {
            r: 2600,
            mils: 1034,
            time: 31.0,
            timeDiff: 0.3,
          },
          {
            r: 2700,
            mils: 993,
            time: 30.3,
            timeDiff: 0.5,
          },
          {
            r: 2800,
            mils: 942,
            time: 29.2,
            timeDiff: 0.6,
          },
          {
            r: 2900,
            mils: 870,
            time: 27.7,
            timeDiff: 1.5,
          },
        ],
      },
    ],
  },
  {
    Shell_type: "SMOKE",
    round_name: "M819",
    rangeTableList: [
      {
        value: 1,
        fix_mil: 11,
        minMaxRange: [200, 750],
        range: [
          {
            r: 200,
            mils: 1463,
            time: 17.7,
            timeDiff: 0.1,
          },
          {
            r: 250,
            mils: 1427,
            time: 17.6,
            timeDiff: 0.1,
          },
          {
            r: 300,
            mils: 1391,
            time: 17.5,
            timeDiff: 0.2,
          },
          {
            r: 350,
            mils: 1352,
            time: 17.3,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1314,
            time: 17.2,
            timeDiff: 0.3,
          },
          {
            r: 450,
            mils: 1271,
            time: 16.9,
            timeDiff: 0.2,
          },
          {
            r: 500,
            mils: 1227,
            time: 16.7,
            timeDiff: 0.3,
          },
          {
            r: 550,
            mils: 1178,
            time: 16.4,
            timeDiff: 0.4,
          },
          {
            r: 600,
            mils: 1124,
            time: 16.0,
            timeDiff: 0.6,
          },
          {
            r: 650,
            mils: 1060,
            time: 15.4,
            timeDiff: 0.7,
          },
          {
            r: 700,
            mils: 982,
            time: 14.7,
            timeDiff: 1.7,
          },
          {
            r: 750,
            mils: 822,
            time: 13.0,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 2,
        fix_mil: 20,
        minMaxRange: [200, 1400],
        range: [
          {
            r: 200,
            mils: 1528,
            time: 24.8,
            timeDiff: 0.1,
          },
          {
            r: 300,
            mils: 1491,
            time: 24.7,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1453,
            time: 24.6,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1414,
            time: 24.4,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1374,
            time: 24.2,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1333,
            time: 24.0,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1289,
            time: 23.7,
            timeDiff: 0.2,
          },
          {
            r: 900,
            mils: 1242,
            time: 23.3,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1191,
            time: 22.9,
            timeDiff: 0.3,
          },
          {
            r: 1100,
            mils: 1133,
            time: 22.3,
            timeDiff: 0.3,
          },
          {
            r: 1200,
            mils: 1067,
            time: 21.6,
            timeDiff: 0.5,
          },
          {
            r: 1300,
            mils: 980,
            time: 20.5,
            timeDiff: 0.9,
          },
          {
            r: 1400,
            mils: 818,
            time: 18.0,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 3,
        fix_mil: 28,
        minMaxRange: [300, 1900],
        range: [
          {
            r: 300,
            mils: 1522,
            time: 29.6,
            timeDiff: 0,
          },
          {
            r: 400,
            mils: 1495,
            time: 29.6,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1468,
            time: 29.5,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1440,
            time: 29.3,
            timeDiff: 0,
          },
          {
            r: 700,
            mils: 1412,
            time: 29.2,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1383,
            time: 29.0,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1354,
            time: 28.9,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1323,
            time: 28.6,
            timeDiff: 0.1,
          },
          {
            r: 1100,
            mils: 1291,
            time: 28.4,
            timeDiff: 0.2,
          },
          {
            r: 1200,
            mils: 1257,
            time: 28.1,
            timeDiff: 0.2,
          },
          {
            r: 1300,
            mils: 1221,
            time: 27.7,
            timeDiff: 0.2,
          },
          {
            r: 1400,
            mils: 1183,
            time: 27.3,
            timeDiff: 0.2,
          },
          {
            r: 1500,
            mils: 1142,
            time: 26.8,
            timeDiff: 0.3,
          },
          {
            r: 1600,
            mils: 1096,
            time: 26.2,
            timeDiff: 0.3,
          },
          {
            r: 1700,
            mils: 1044,
            time: 25.5,
            timeDiff: 0.5,
          },
          {
            r: 1800,
            mils: 980,
            time: 24.5,
            timeDiff: 0.6,
          },
          {
            r: 1900,
            mils: 892,
            time: 23.0,
            timeDiff: 1.5,
          },
        ],
      },
      {
        value: 4,
        fix_mil: 35,
        minMaxRange: [400, 2400],
        range: [
          {
            r: 400,
            mils: 1517,
            time: 33.6,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1495,
            time: 33.5,
            timeDiff: 0,
          },
          {
            r: 600,
            mils: 1474,
            time: 33.5,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1452,
            time: 33.4,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1429,
            time: 33.2,
            timeDiff: 0,
          },
          {
            r: 900,
            mils: 1407,
            time: 33.1,
            timeDiff: 0,
          },
          {
            r: 1000,
            mils: 1383,
            time: 33.0,
            timeDiff: 0.1,
          },
          {
            r: 1100,
            mils: 1360,
            time: 32.8,
            timeDiff: 0.1,
          },
          {
            r: 1200,
            mils: 1335,
            time: 32.6,
            timeDiff: 0.1,
          },
          {
            r: 1300,
            mils: 1310,
            time: 32.4,
            timeDiff: 0.1,
          },
          {
            r: 1400,
            mils: 1284,
            time: 32.1,
            timeDiff: 0.1,
          },
          {
            r: 1500,
            mils: 1257,
            time: 31.9,
            timeDiff: 0.1,
          },
          {
            r: 1600,
            mils: 1228,
            time: 31.5,
            timeDiff: 0.1,
          },
          {
            r: 1700,
            mils: 1199,
            time: 31.2,
            timeDiff: 0.2,
          },
          {
            r: 1800,
            mils: 1166,
            time: 30.8,
            timeDiff: 0.2,
          },
          {
            r: 1900,
            mils: 1132,
            time: 30.3,
            timeDiff: 0.2,
          },
          {
            r: 2000,
            mils: 1096,
            time: 29.8,
            timeDiff: 0.3,
          },
          {
            r: 2100,
            mils: 1096,
            time: 29.6,
            timeDiff: 0.3,
          },
          {
            r: 2200,
            mils: 1055,
            time: 29.1,
            timeDiff: 0.5,
          },
          {
            r: 2300,
            mils: 1008,
            time: 30.3,
            timeDiff: 0.7,
          },
          {
            r: 2400,
            mils: 871,
            time: 25.8,
            timeDiff: 1.5,
          },
        ],
      },
    ],
  },
  {
    Shell_type: "ILLUMINATION",
    round_name: "M853A1",
    rangeTableList: [
      {
        value: 1,
        fix_mil: 11,
        minMaxRange: [200, 750],
        range: [
          {
            r: 200,
            mils: 1463,
            time: 18.1,
            timeDiff: 0.1,
          },
          {
            r: 250,
            mils: 1428,
            time: 18.0,
            timeDiff: 0.1,
          },
          {
            r: 300,
            mils: 1391,
            time: 17.9,
            timeDiff: 0.2,
          },
          {
            r: 350,
            mils: 1352,
            time: 17.7,
            timeDiff: 0.2,
          },
          {
            r: 400,
            mils: 1312,
            time: 17.5,
            timeDiff: 0.2,
          },
          {
            r: 450,
            mils: 1269,
            time: 17.3,
            timeDiff: 0.3,
          },
          {
            r: 500,
            mils: 1224,
            time: 17.0,
            timeDiff: 0.3,
          },
          {
            r: 550,
            mils: 1175,
            time: 16.7,
            timeDiff: 0.4,
          },
          {
            r: 600,
            mils: 1120,
            time: 16.3,
            timeDiff: 0.6,
          },
          {
            r: 650,
            mils: 1055,
            time: 15.7,
            timeDiff: 0.7,
          },
          {
            r: 700,
            mils: 975,
            time: 15.0,
            timeDiff: 1.7,
          },
          {
            r: 750,
            mils: 823,
            time: 16.7,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 2,
        fix_mil: 21,
        minMaxRange: [200, 1400],
        range: [
          {
            r: 200,
            mils: 1529,
            time: 26.2,
            timeDiff: 0.1,
          },
          {
            r: 300,
            mils: 1493,
            time: 26.1,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1457,
            time: 26.0,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1419,
            time: 25.8,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1379,
            time: 25.8,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1338,
            time: 25.4,
            timeDiff: 0.2,
          },
          {
            r: 800,
            mils: 1295,
            time: 25.1,
            timeDiff: 0.2,
          },
          {
            r: 900,
            mils: 1249,
            time: 24.7,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1199,
            time: 24.3,
            timeDiff: 0.3,
          },
          {
            r: 1100,
            mils: 1144,
            time: 23.7,
            timeDiff: 0.3,
          },
          {
            r: 1200,
            mils: 1081,
            time: 23.0,
            timeDiff: 0.4,
          },
          {
            r: 1300,
            mils: 1005,
            time: 23.0,
            timeDiff: 0.6,
          },
          {
            r: 1400,
            mils: 900,
            time: 20.5,
            timeDiff: 1.6,
          },
        ],
      },
      {
        value: 3,
        fix_mil: 29,
        minMaxRange: [300, 1900],
        range: [
          {
            r: 300,
            mils: 1521,
            time: 31.1,
            timeDiff: 0,
          },
          {
            r: 400,
            mils: 1494,
            time: 31.1,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1466,
            time: 31.0,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1438,
            time: 30.8,
            timeDiff: 0,
          },
          {
            r: 700,
            mils: 1409,
            time: 30.7,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1380,
            time: 30.5,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1349,
            time: 30.3,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1317,
            time: 30.1,
            timeDiff: 0.2,
          },
          {
            r: 1100,
            mils: 1284,
            time: 29.8,
            timeDiff: 0.2,
          },
          {
            r: 1200,
            mils: 1249,
            time: 29.4,
            timeDiff: 0.2,
          },
          {
            r: 1212,
            mils: 1031,
            time: 29.1,
            timeDiff: 0.3,
          },
          {
            r: 1400,
            mils: 1172,
            time: 28.6,
            timeDiff: 0.2,
          },
          {
            r: 1500,
            mils: 1128,
            time: 28.1,
            timeDiff: 0.3,
          },
          {
            r: 1600,
            mils: 1081,
            time: 27.4,
            timeDiff: 0.3,
          },
          {
            r: 1700,
            mils: 1027,
            time: 26.6,
            timeDiff: 0.4,
          },
          {
            r: 1800,
            mils: 962,
            time: 25.6,
            timeDiff: 0.7,
          },
          {
            r: 1900,
            mils: 875,
            time: 24.13,
            timeDiff: 1.3,
          },
        ],
      },
      {
        value: 4,
        fix_mil: 36,
        minMaxRange: [400, 2400],
        range: [
          {
            r: 400,
            mils: 1515,
            time: 35.7,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1493,
            time: 35.7,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1471,
            time: 35.6,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1448,
            time: 35.5,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1426,
            time: 35.4,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1402,
            time: 35.2,
            timeDiff: 0.1,
          },
          {
            r: 1000,
            mils: 1378,
            time: 35.0,
            timeDiff: 0.1,
          },
          {
            r: 1100,
            mils: 1353,
            time: 34.8,
            timeDiff: 0.1,
          },
          {
            r: 1200,
            mils: 1328,
            time: 34.6,
            timeDiff: 0.1,
          },
          {
            r: 1300,
            mils: 1301,
            time: 34.4,
            timeDiff: 0.1,
          },
          {
            r: 1400,
            mils: 1274,
            time: 34.1,
            timeDiff: 0.1,
          },
          {
            r: 1500,
            mils: 1245,
            time: 33.8,
            timeDiff: 0.2,
          },
          {
            r: 1600,
            mils: 1215,
            time: 33.4,
            timeDiff: 0.1,
          },
          {
            r: 1700,
            mils: 1184,
            time: 33.0,
            timeDiff: 0.3,
          },
          {
            r: 1800,
            mils: 1151,
            time: 32.6,
            timeDiff: 0.3,
          },
          {
            r: 1900,
            mils: 1115,
            time: 32.1,
            timeDiff: 0.3,
          },
          {
            r: 2000,
            mils: 1076,
            time: 31.5,
            timeDiff: 0.4,
          },
          {
            r: 2100,
            mils: 1033,
            time: 30.8,
            timeDiff: 0.4,
          },
          {
            r: 2200,
            mils: 985,
            time: 29.9,
            timeDiff: 0.5,
          },
          {
            r: 2200,
            mils: 928,
            time: 28.8,
            timeDiff: 0.6,
          },
          {
            r: 2200,
            mils: 855,
            time: 27.4,
            timeDiff: 1.1,
          },
        ],
      },
    ],
  },
];
