export const RangeTable = [
  {
    Shell_type: "HE",
    rangeTableList: [
      {
        value: 0,
        fix_mil: 8,
        minMaxRange: [50, 500],
        range: [
          {
            r: 50,
            mils: 1455,
            time: 15.0,
            timeDiff: 0,
          },
          {
            r: 100,
            mils: 1411,
            time: 15.0,
            timeDiff: 0.1,
          },
          {
            r: 150,
            mils: 1365,
            time: 14.9,
            timeDiff: 0.1,
          },
          {
            r: 200,
            mils: 1318,
            time: 14.8,
            timeDiff: 0.2,
          },
          {
            r: 250,
            mils: 1268,
            time: 14.6,
            timeDiff: 0.2,
          },
          {
            r: 300,
            mils: 1217,
            time: 14.4,
            timeDiff: 0.3,
          },
          {
            r: 350,
            mils: 1159,
            time: 14.1,
            timeDiff: 0.4,
          },
          {
            r: 400,
            mils: 1095,
            time: 13.7,
            timeDiff: 0.5,
          },
          {
            r: 450,
            mils: 1023,
            time: 13.2,
            timeDiff: 0.8,
          },
          {
            r: 500,
            mils: 1212,
            time: 12.4,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 1,
        fix_mil: 13,
        minMaxRange: [100, 800],
        range: [
          {
            r: 100,
            mils: 1446,
            time: 19.5,
            timeDiff: 0.1,
          },
          {
            r: 200,
            mils: 1392,
            time: 19.4,
            timeDiff: 0.1,
          },
          {
            r: 300,
            mils: 1335,
            time: 19.2,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1275,
            time: 18.9,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1212,
            time: 18.6,
            timeDiff: 0.2,
          },
          {
            r: 600,
            mils: 1141,
            time: 18.1,
            timeDiff: 0.3,
          },
          {
            r: 700,
            mils: 1058,
            time: 17.4,
            timeDiff: 0.4,
          },
          {
            r: 800,
            mils: 952,
            time: 16.4,
            timeDiff: 0.9,
          },
        ],
      },
      {
        value: 2,
        fix_mil: 19,
        minMaxRange: [200, 1400],
        range: [
          {
            r: 200,
            mils: 1432,
            time: 24.8,
            timeDiff: 0,
          },
          {
            r: 300,
            mils: 1397,
            time: 24.7,
            timeDiff: 0,
          },
          {
            r: 400,
            mils: 1362,
            time: 24.6,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1325,
            time: 24.4,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1288,
            time: 24.2,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1248,
            time: 24.0,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1207,
            time: 23.7,
            timeDiff: 0.2,
          },
          {
            r: 900,
            mils: 1162,
            time: 23.3,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1114,
            time: 22.9,
            timeDiff: 0.3,
          },
          {
            r: 1100,
            mils: 1060,
            time: 22.3,
            timeDiff: 0.3,
          },
          {
            r: 1200,
            mils: 997,
            time: 21.5,
            timeDiff: 0.4,
          },
          {
            r: 1300,
            mils: 914,
            time: 20.4,
            timeDiff: 0.8,
          },
          {
            r: 1400,
            mils: 755,
            time: 17.8,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 3,
        fix_mil: 27,
        minMaxRange: [300, 1800],
        range: [
          {
            r: 300,
            mils: 1423,
            time: 28.9,
            timeDiff: 0,
          },
          {
            r: 400,
            mils: 1397,
            time: 28.9,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1370,
            time: 28.8,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1343,
            time: 28.6,
            timeDiff: 0,
          },
          {
            r: 700,
            mils: 1315,
            time: 28.5,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1286,
            time: 28.3,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1257,
            time: 28.1,
            timeDiff: 0.1,
          },
          {
            r: 1000,
            mils: 1226,
            time: 27.9,
            timeDiff: 0.2,
          },
          {
            r: 1100,
            mils: 1193,
            time: 27.6,
            timeDiff: 0.2,
          },
          {
            r: 1200,
            mils: 1159,
            time: 27.2,
            timeDiff: 0.2,
          },
          {
            r: 1300,
            mils: 1123,
            time: 26.8,
            timeDiff: 0.2,
          },
          {
            r: 1400,
            mils: 1084,
            time: 26.4,
            timeDiff: 0.3,
          },
          {
            r: 1500,
            mils: 1040,
            time: 25.8,
            timeDiff: 0.3,
          },
          {
            r: 1600,
            mils: 991,
            time: 25.1,
            timeDiff: 0.4,
          },
          {
            r: 1700,
            mils: 932,
            time: 24.2,
            timeDiff: 0.6,
          },
          {
            r: 1800,
            mils: 851,
            time: 22.8,
            timeDiff: 1.3,
          },
        ],
      },
      {
        value: 4,
        fix_mil: 34,
        minMaxRange: [400, 2300],
        range: [
          {
            r: 400,
            mils: 1418,
            time: 32.9,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1398,
            time: 32.9,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1376,
            time: 32.8,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1355,
            time: 32.7,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1333,
            time: 32.6,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1311,
            time: 32.4,
            timeDiff: 0.1,
          },
          {
            r: 1000,
            mils: 1288,
            time: 32.2,
            timeDiff: 0,
          },
          {
            r: 1100,
            mils: 1264,
            time: 32.1,
            timeDiff: 0.1,
          },
          {
            r: 1200,
            mils: 1240,
            time: 31.8,
            timeDiff: 0.1,
          },
          {
            r: 1300,
            mils: 1215,
            time: 31.6,
            timeDiff: 0.1,
          },
          {
            r: 1400,
            mils: 1189,
            time: 31.3,
            timeDiff: 0.1,
          },
          {
            r: 1500,
            mils: 1161,
            time: 31.0,
            timeDiff: 0.1,
          },
          {
            r: 1600,
            mils: 1133,
            time: 30.7,
            timeDiff: 0.2,
          },
          {
            r: 1700,
            mils: 1102,
            time: 30.3,
            timeDiff: 0.2,
          },
          {
            r: 1800,
            mils: 1069,
            time: 29.8,
            timeDiff: 0.2,
          },
          {
            r: 1900,
            mils: 1034,
            time: 29.3,
            timeDiff: 0.3,
          },
          {
            r: 2000,
            mils: 995,
            time: 28.7,
            timeDiff: 0.4,
          },
          {
            r: 2100,
            mils: 950,
            time: 27.9,
            timeDiff: 0.5,
          },
          {
            r: 2200,
            mils: 896,
            time: 26.9,
            timeDiff: 0.7,
          },
          {
            r: 2300,
            mils: 820,
            time: 25.3,
            timeDiff: 1.4,
          },
        ],
      },
    ],
  },
  {
    Shell_type: "SMOKE",
    rangeTableList: [
      {
        value: 0,
        fix_mil: 7,
        minMaxRange: [50, 450],
        range: [
          {
            r: 50,
            mils: 1450,
            time: 14.1,
            timeDiff: 0.1,
          },
          {
            r: 100,
            mils: 1399,
            time: 14.0,
            timeDiff: 0.1,
          },
          {
            r: 150,
            mils: 1347,
            time: 13.9,
            timeDiff: 0.1,
          },
          {
            r: 200,
            mils: 1292,
            time: 13.8,
            timeDiff: 0.2,
          },
          {
            r: 250,
            mils: 1235,
            time: 13.6,
            timeDiff: 0.3,
          },
          {
            r: 300,
            mils: 1172,
            time: 13.3,
            timeDiff: 0.4,
          },
          {
            r: 350,
            mils: 1102,
            time: 12.9,
            timeDiff: 0.5,
          },
          {
            r: 400,
            mils: 1020,
            time: 12.4,
            timeDiff: 1,
          },
          {
            r: 450,
            mils: 898,
            time: 11.4,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 1,
        fix_mil: 12,
        minMaxRange: [200, 800],
        range: [
          {
            r: 200,
            mils: 1381,
            time: 18.4,
            timeDiff: 0.1,
          },
          {
            r: 300,
            mils: 1319,
            time: 18.2,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1252,
            time: 17.9,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1179,
            time: 17.5,
            timeDiff: 0.2,
          },
          {
            r: 600,
            mils: 1097,
            time: 16.9,
            timeDiff: 0.4,
          },
          {
            r: 700,
            mils: 993,
            time: 16.0,
            timeDiff: 0.7,
          },
          {
            r: 800,
            mils: 805,
            time: 13.9,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 2,
        fix_mil: 18,
        minMaxRange: [300, 1200],
        range: [
          {
            r: 300,
            mils: 1387,
            time: 23.5,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1348,
            time: 23.3,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1308,
            time: 23.2,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1266,
            time: 22.9,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1222,
            time: 22.7,
            timeDiff: 0.2,
          },
          {
            r: 800,
            mils: 1175,
            time: 22.3,
            timeDiff: 0.2,
          },
          {
            r: 900,
            mils: 1123,
            time: 21.8,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1065,
            time: 21.3,
            timeDiff: 0.4,
          },
          {
            r: 1100,
            mils: 994,
            time: 20.4,
            timeDiff: 0.5,
          },
          {
            r: 1200,
            mils: 902,
            time: 19.2,
            timeDiff: 0.9,
          },
        ],
      },
      {
        value: 3,
        fix_mil: 24,
        minMaxRange: [400, 1700],
        range: [
          {
            r: 400,
            mils: 1387,
            time: 27.3,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1357,
            time: 27.2,
            timeDiff: 0,
          },
          {
            r: 600,
            mils: 1327,
            time: 27.1,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1296,
            time: 26.9,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1264,
            time: 26.7,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1231,
            time: 26.5,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1196,
            time: 26.2,
            timeDiff: 0.2,
          },
          {
            r: 1100,
            mils: 1159,
            time: 25.8,
            timeDiff: 0.2,
          },
          {
            r: 1200,
            mils: 1119,
            time: 25.4,
            timeDiff: 0.2,
          },
          {
            r: 1300,
            mils: 1075,
            time: 24.9,
            timeDiff: 0.3,
          },
          {
            r: 1400,
            mils: 1026,
            time: 24.3,
            timeDiff: 0.4,
          },
          {
            r: 1500,
            mils: 969,
            time: 23.5,
            timeDiff: 0.6,
          },
          {
            r: 1600,
            mils: 896,
            time: 22.3,
            timeDiff: 0.8,
          },
          {
            r: 1700,
            mils: 753,
            time: 19.8,
            timeDiff: 0,
          },
        ],
      },
    ],
  },
  {
    Shell_type: "FLARE",
    rangeTableList: [
      {
        value: 1,
        fix_mil: 9,
        minMaxRange: [100, 600],
        range: [
          {
            r: 100,
            mils: 1421,
            time: 16.4,
            timeDiff: 0.1,
          },
          {
            r: 150,
            mils: 1381,
            time: 16.3,
            timeDiff: 0.1,
          },
          {
            r: 200,
            mils: 1339,
            time: 16.2,
            timeDiff: 0.2,
          },
          {
            r: 250,
            mils: 1296,
            time: 16.1,
            timeDiff: 0.2,
          },
          {
            r: 300,
            mils: 1251,
            time: 15.9,
            timeDiff: 0.2,
          },
          {
            r: 350,
            mils: 1251,
            time: 15.7,
            timeDiff: 0.3,
          },
          {
            r: 400,
            mils: 1151,
            time: 15.4,
            timeDiff: 0.4,
          },
          {
            r: 450,
            mils: 1093,
            time: 15.0,
            timeDiff: 0.5,
          },
          {
            r: 500,
            mils: 1028,
            time: 14.5,
            timeDiff: 0.7,
          },
          {
            r: 550,
            mils: 945,
            time: 13.8,
            timeDiff: 1.5,
          },
          {
            r: 600,
            mils: 799,
            time: 12.3,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 2,
        fix_mil: 17,
        minMaxRange: [200, 1100],
        range: [
          {
            r: 200,
            mils: 1417,
            time: 23.6,
            timeDiff: 0,
          },
          {
            r: 300,
            mils: 1374,
            time: 23.5,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1330,
            time: 23.3,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1284,
            time: 23.1,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1234,
            time: 22.8,
            timeDiff: 0.2,
          },
          {
            r: 700,
            mils: 1182,
            time: 22.4,
            timeDiff: 0.2,
          },
          {
            r: 800,
            mils: 1124,
            time: 21.9,
            timeDiff: 0.3,
          },
          {
            r: 900,
            mils: 1057,
            time: 21.3,
            timeDiff: 0.4,
          },
          {
            r: 1000,
            mils: 979,
            time: 20.4,
            timeDiff: 0.6,
          },
          {
            r: 1100,
            mils: 870,
            time: 18.9,
            timeDiff: 1.3,
          },
        ],
      },
      {
        value: 3,
        fix_mil: 24,
        minMaxRange: [300, 1600],
        range: [
          {
            r: 300,
            mils: 1411,
            time: 29.0,
            timeDiff: 0.1,
          },
          {
            r: 400,
            mils: 1380,
            time: 28.9,
            timeDiff: 0.1,
          },
          {
            r: 500,
            mils: 1348,
            time: 28.7,
            timeDiff: 0.1,
          },
          {
            r: 600,
            mils: 1315,
            time: 28.6,
            timeDiff: 0.1,
          },
          {
            r: 700,
            mils: 1281,
            time: 28.4,
            timeDiff: 0.2,
          },
          {
            r: 800,
            mils: 1246,
            time: 28.1,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1209,
            time: 27.8,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1170,
            time: 27.4,
            timeDiff: 0.2,
          },
          {
            r: 1100,
            mils: 1128,
            time: 27.0,
            timeDiff: 0.3,
          },
          {
            r: 1200,
            mils: 1082,
            time: 26.5,
            timeDiff: 0.3,
          },
          {
            r: 1300,
            mils: 1031,
            time: 25.8,
            timeDiff: 0.4,
          },
          {
            r: 1400,
            mils: 973,
            time: 25.0,
            timeDiff: 0.5,
          },
          {
            r: 1500,
            mils: 903,
            time: 23.9,
            timeDiff: 0.7,
          },
          {
            r: 1600,
            mils: 807,
            time: 22.3,
            timeDiff: 0,
          },
        ],
      },
      {
        value: 4,
        fix_mil: 32,
        minMaxRange: [400, 2200],
        range: [
          {
            r: 400,
            mils: 1411,
            time: 35.3,
            timeDiff: 0,
          },
          {
            r: 500,
            mils: 1388,
            time: 35.2,
            timeDiff: 0,
          },
          {
            r: 600,
            mils: 1364,
            time: 35.1,
            timeDiff: 0,
          },
          {
            r: 700,
            mils: 1341,
            time: 35.0,
            timeDiff: 0.1,
          },
          {
            r: 800,
            mils: 1316,
            time: 34.8,
            timeDiff: 0.1,
          },
          {
            r: 900,
            mils: 1291,
            time: 34.7,
            timeDiff: 0.2,
          },
          {
            r: 1000,
            mils: 1265,
            time: 34.4,
            timeDiff: 0.1,
          },
          {
            r: 1100,
            mils: 1238,
            time: 34.2,
            timeDiff: 0.1,
          },
          {
            r: 1200,
            mils: 1210,
            time: 33.9,
            timeDiff: 0.1,
          },
          {
            r: 1300,
            mils: 1181,
            time: 33.6,
            timeDiff: 0.2,
          },
          {
            r: 1400,
            mils: 1150,
            time: 33.2,
            timeDiff: 0.2,
          },
          {
            r: 1500,
            mils: 1119,
            time: 32.8,
            timeDiff: 0.2,
          },
          {
            r: 1600,
            mils: 1085,
            time: 32.4,
            timeDiff: 0.3,
          },
          {
            r: 1700,
            mils: 1048,
            time: 31.8,
            timeDiff: 0.3,
          },
          {
            r: 1800,
            mils: 1009,
            time: 31.2,
            timeDiff: 0.3,
          },
          {
            r: 1900,
            mils: 965,
            time: 30.4,
            timeDiff: 0.4,
          },
          {
            r: 2000,
            mils: 917,
            time: 29.6,
            timeDiff: 0.5,
          },
          {
            r: 2100,
            mils: 860,
            time: 28.4,
            timeDiff: 0.7,
          },
          {
            r: 2200,
            mils: 787,
            time: 26.9,
            timeDiff: 0,
          },
        ],
      },
    ],
  },
];
